### ISSUE TITLE
update tor and nginx.

### ISSUE THREAD

**Issue by jessssgreennj** [Yanik39/TORNet#2]
Hello. Great Build everything works) How do I update the tor and nginx?

**Comment by quantumalchemy** [comment]
Hey how did you get it to work?
my  docker run fails using the cmd listed in the readme.. ends with NGINX exiting / failing (see issue & below)
Its Ok until  'Vanguards' is run then  --> " NGINX (exit status 1; not expected)  "
so proly something wrong with NGINX config?  php-fpm / tor config?  

- Thanks


2021-08-17 18:59:10,820 INFO spawned: 'Vanguards' with pid 939
2021-08-17 18:59:10,852 INFO exited: NGINX (exit status 1; not expected)

**Comment by jessssgreennj** [comment]
Hello. I solved my problem like this:
`docker exec -u root -it TORNet bash
nano etc/apt/sources.list.d./tor.list
change:
deb https://deb.torproject.org/torproject.org buster main
deb-src https://deb.torproject.org/torproject.org buster main
to
deb https://deb.torproject.org/torproject.org tor-nightly-0.4.6.x-buster main
deb-src https://deb.torproject.org/torproject.org tor-nightly-0.4.6.x-buster main
can be changed to another version select here: 
https://deb.torproject.org/torproject.org/dists/`
save file.
further
In a terminal in a container, enter:
`apt update`
`apt install tor`
Good job)

**Comment by Yanik39** [comment]
Hi, sorry for extremely late response :)

I did upgrade everything from debian buster to bullseye.
So again everything is now up to date.
